language: node_js
node_js:
- 5.6
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: OZ+OFULqrm8WkF1p0pVsEYWr36tjnMAcX5WbUchWk32sqEY+aeViExur5m3yBc+VWVwkI2e8/T0h1E4/74V2/y8qCfEMgRcDjD7y7hQGJQd98uKb6OkvOeYbRrcMuke9jDbqmMBofptBSLb3ZMz5aI2wu55HSwyUv5aWEWusBPU=
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: Z291fOPTg/3XEw/pBgA/9s4y0cyc/CkFdn0YRIbLyk66y9FWVIwacytGsl2hs2+hQZXXizrx6GK+NEUCuOB+CpFzFi9sE0+b+HIQ/hAnPC8L9AdGWKiIS6skekjJC+ZhQRJq+/DnSe8/N8Mr3YA6rO3PiqHlVJ5787y5vId4w2E=
